/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author jrswa
 */
public class ManageAccounts extends javax.swing.JPanel {
    JPanel userProcessContainer;
    PersonDirectory personDirectory;

    /**
     * Creates new form ManageAccounts
     */
    public ManageAccounts(JPanel container, PersonDirectory directory) {
        initComponents();
        userProcessContainer = container;
        personDirectory= directory;
        
        populateTable(); //populate Jtable with account directory
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtnm = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        viewdetailsbtn = new javax.swing.JButton();
        delaccbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        backbtnm.setBackground(new java.awt.Color(0, 0, 0));
        backbtnm.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        backbtnm.setForeground(new java.awt.Color(204, 204, 255));
        backbtnm.setText("<<<Back");
        backbtnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnmActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(0, 0, 0));
        searchbtn.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(204, 204, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        viewdetailsbtn.setBackground(new java.awt.Color(0, 0, 0));
        viewdetailsbtn.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        viewdetailsbtn.setForeground(new java.awt.Color(204, 204, 255));
        viewdetailsbtn.setText("View Details");
        viewdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailsbtnActionPerformed(evt);
            }
        });

        delaccbtn.setBackground(new java.awt.Color(0, 0, 0));
        delaccbtn.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        delaccbtn.setForeground(new java.awt.Color(204, 204, 255));
        delaccbtn.setText("Delete Account");
        delaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delaccbtnActionPerformed(evt);
            }
        });

        tblAccounts.setBackground(new java.awt.Color(0, 0, 0));
        tblAccounts.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        tblAccounts.setForeground(new java.awt.Color(204, 204, 255));
        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bank Name", "Routing Number", "Account Number", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tblAccounts);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Account");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backbtnm, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(viewdetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {delaccbtn, searchbtn, viewdetailsbtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbtnm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewdetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {delaccbtn, searchbtn, viewdetailsbtn});

    }// </editor-fold>//GEN-END:initComponents

    private void backbtnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnmActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
                                           
    }//GEN-LAST:event_backbtnmActionPerformed

    private void delaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delaccbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAccounts.getSelectedRow();
        
        if(selectedRow>=0)
        {
            
            int dialogButton = JOptionPane.YES_NO_OPTION;//option dialog box for deleting the account
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the account?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Person selectedAccount=(Person)tblAccounts.getValueAt(selectedRow, 0);
                personDirectory.deleteAccount(selectedAccount);//methhod declared in account directory
                populateTable();//refresh list
            }
            
            else//if no is an option
            {
                JOptionPane.showMessageDialog(null,"Please select an account from the list","Warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        else// if no row is selected
        {
            JOptionPane.showMessageDialog(null,"Please select an account from the list","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delaccbtnActionPerformed

    private void viewdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailsbtnActionPerformed
        // TODO add your handling code here:
        // opening view details for the selected account
        int selectedRow = tblAccounts.getSelectedRow();
        //check if user selected any account
        if(selectedRow>= 0){
            
            Person selectedAccount= (Person) tblAccounts.getValueAt(selectedRow,0);//account which user selected
            
            ViewAccount panel= new ViewAccount(userProcessContainer,personDirectory,selectedAccount);
            userProcessContainer.add("ViewAccount",panel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {//if row is not selected
            JOptionPane.showMessageDialog(null, "You need to select an account to view account details","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewdetailsbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        if(!txtsearch.getText().isBlank())
        {
            String accountNumber = txtsearch.getText();
            Person foundAccount = personDirectory.searchPerson(accountNumber);
            
            if(foundAccount!=null)//if not empty, according to the method in account directory 
            {
                ViewAccount panel= new ViewAccount(userProcessContainer,personDirectory,foundAccount);
                userProcessContainer.add("ViewAccount",panel);
                CardLayout layout=(CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Account not found. Try again");
                //if account is not found among directory
            }
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Please type account number to view","Warning",JOptionPane.WARNING_MESSAGE);
            //if search text field is empty
        }
        
    }//GEN-LAST:event_searchbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtnm;
    private javax.swing.JButton delaccbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JButton viewdetailsbtn;
    // End of variables declaration//GEN-END:variables

    void populateTable() {
      DefaultTableModel model = (DefaultTableModel) tblAccounts.getModel();
      model.setRowCount(0);
      
      for(Person a : accountDirectory.getAccount()){
          
          Object[] row = new Object[4];
          row[0] = a;
          row[1] = a.getRountingNumber();
          row[2]= a.getAccountNumber();
          row[3]= String.valueOf(a.getBalance());
          
          model.addRow(row);
      }
    }
}
