/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.PersonDirectory;

import model.Person;
import model.PersonDirectory;
import ui.PersonManager.CreatePersson;
/**
 *
 * @author jrswa
 */
public class PersonMngWorkArea extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    PersonDirectory accountDirectory;

    /**
     * Creates new form AccountMngWorkArea
     */
    public PersonMngWorkArea(JPanel container, PersonDirectory directory) {
        initComponents();
        userProcessContainer = container;
        accountDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createaccbtn = new javax.swing.JButton();
        mngaccbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1063, 547));

        createaccbtn.setBackground(new java.awt.Color(0, 0, 0));
        createaccbtn.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        createaccbtn.setForeground(new java.awt.Color(204, 204, 255));
        createaccbtn.setText("Create Account");
        createaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccbtnActionPerformed(evt);
            }
        });

        mngaccbtn.setBackground(new java.awt.Color(0, 0, 0));
        mngaccbtn.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        mngaccbtn.setForeground(new java.awt.Color(204, 204, 255));
        mngaccbtn.setText("Manage Account");
        mngaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngaccbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(createaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(mngaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createaccbtn, mngaccbtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mngaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createaccbtn, mngaccbtn});

    }// </editor-fold>//GEN-END:initComponents

    private void createaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccbtnActionPerformed
        // TODO add your handling code here:
        CreatePersson panel = new CreatePersson(userProcessContainer,accountDirectory);
        userProcessContainer.add("CreateAccount", panel);// adding this panel to container
        
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);//adding create acc to next panel
    }//GEN-LAST:event_createaccbtnActionPerformed

    private void mngaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngaccbtnActionPerformed
        // TODO add your handling code here:
        ManageAccounts panel = new ManageAccounts(userProcessContainer,accountDirectory);
        userProcessContainer.add("ManageAccounts", panel);
        
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);//adding manage account to next panel
    }//GEN-LAST:event_mngaccbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createaccbtn;
    private javax.swing.JButton mngaccbtn;
    // End of variables declaration//GEN-END:variables
}
