/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author jrswa
 */
public class ViewPerson extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private PersonDirectory accountDirectory;
    private Person person;

    /**
     * Creates new form ViewAccount
     */
    public ViewPerson(JPanel userProcessContainer,PersonDirectory accountDirectory,Person person) {
        
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.person = person;
        
        refreshTextFields();// populate text fields
        setViewMode();//view mode
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        savebtnv = new javax.swing.JButton();
        updatebtnv = new javax.swing.JButton();
        backbtnv = new javax.swing.JButton();
        accountlb = new javax.swing.JLabel();
        banknamelb = new javax.swing.JLabel();
        balancelb = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        JPanelHomeAdd = new javax.swing.JPanel();
        cityLbl = new javax.swing.JLabel();
        zipLBL = new javax.swing.JLabel();
        HtxtStreetAdd = new javax.swing.JTextField();
        HtxtUnitNo = new javax.swing.JTextField();
        HtxtCity = new javax.swing.JTextField();
        HtxtPhone = new javax.swing.JTextField();
        streetaddLBL = new javax.swing.JLabel();
        unitLBL = new javax.swing.JLabel();
        phoneLBL = new javax.swing.JLabel();
        stateLBL = new javax.swing.JLabel();
        HtxtZip = new javax.swing.JTextField();
        HtxtState = new javax.swing.JTextField();
        routinglb = new javax.swing.JLabel();
        weightlb1 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JPanelWorkAdd1 = new javax.swing.JPanel();
        cityLbl3 = new javax.swing.JLabel();
        zipLBL3 = new javax.swing.JLabel();
        WtxtStreetAdd2 = new javax.swing.JTextField();
        WtxtUnitNo2 = new javax.swing.JTextField();
        WtxtCity2 = new javax.swing.JTextField();
        WtxtPhone2 = new javax.swing.JTextField();
        streetaddLBL3 = new javax.swing.JLabel();
        unitLBL3 = new javax.swing.JLabel();
        phoneLBL3 = new javax.swing.JLabel();
        stateLBL3 = new javax.swing.JLabel();
        WtxtZip2 = new javax.swing.JTextField();
        WtxtState2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View person");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        savebtnv.setBackground(new java.awt.Color(0, 0, 0));
        savebtnv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        savebtnv.setForeground(new java.awt.Color(204, 204, 255));
        savebtnv.setText("Save");
        savebtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnvActionPerformed(evt);
            }
        });

        updatebtnv.setBackground(new java.awt.Color(0, 0, 0));
        updatebtnv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        updatebtnv.setForeground(new java.awt.Color(204, 204, 255));
        updatebtnv.setText("Update");
        updatebtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnvActionPerformed(evt);
            }
        });

        backbtnv.setBackground(new java.awt.Color(0, 0, 0));
        backbtnv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        backbtnv.setForeground(new java.awt.Color(204, 204, 255));
        backbtnv.setText("<<<Back");
        backbtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnvActionPerformed(evt);
            }
        });

        accountlb.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        accountlb.setForeground(new java.awt.Color(0, 51, 51));
        accountlb.setText("Last name");

        banknamelb.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        banknamelb.setForeground(new java.awt.Color(0, 51, 51));
        banknamelb.setText("social security number");

        balancelb.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        balancelb.setForeground(new java.awt.Color(0, 51, 51));
        balancelb.setText("age");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setText("Home Address");

        JPanelHomeAdd.setBackground(new java.awt.Color(255, 255, 255));

        cityLbl.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        cityLbl.setForeground(new java.awt.Color(0, 51, 51));
        cityLbl.setText("city");

        zipLBL.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        zipLBL.setForeground(new java.awt.Color(0, 51, 51));
        zipLBL.setText("zip code");

        HtxtStreetAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HtxtStreetAddActionPerformed(evt);
            }
        });

        streetaddLBL.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        streetaddLBL.setForeground(new java.awt.Color(0, 51, 51));
        streetaddLBL.setText("Street address");

        unitLBL.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        unitLBL.setForeground(new java.awt.Color(0, 51, 51));
        unitLBL.setText("unit number");

        phoneLBL.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        phoneLBL.setForeground(new java.awt.Color(0, 51, 51));
        phoneLBL.setText("Phone No.");

        stateLBL.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        stateLBL.setForeground(new java.awt.Color(0, 51, 51));
        stateLBL.setText("State");

        javax.swing.GroupLayout JPanelHomeAddLayout = new javax.swing.GroupLayout(JPanelHomeAdd);
        JPanelHomeAdd.setLayout(JPanelHomeAddLayout);
        JPanelHomeAddLayout.setHorizontalGroup(
            JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHomeAddLayout.createSequentialGroup()
                .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JPanelHomeAddLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(HtxtState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(HtxtZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(HtxtPhone, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(JPanelHomeAddLayout.createSequentialGroup()
                            .addGap(245, 245, 245)
                            .addComponent(HtxtUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelHomeAddLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPanelHomeAddLayout.createSequentialGroup()
                                    .addComponent(cityLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(unitLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JPanelHomeAddLayout.createSequentialGroup()
                                    .addComponent(streetaddLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HtxtStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(zipLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        JPanelHomeAddLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {HtxtCity, HtxtPhone, HtxtState, HtxtStreetAdd, HtxtUnitNo, HtxtZip});

        JPanelHomeAddLayout.setVerticalGroup(
            JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHomeAddLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HtxtStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetaddLBL))
                .addGap(18, 18, 18)
                .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HtxtUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitLBL))
                .addGap(18, 18, 18)
                .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLbl))
                .addGap(18, 18, 18)
                .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HtxtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLBL))
                .addGap(18, 18, 18)
                .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HtxtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipLBL))
                .addGap(18, 18, 18)
                .addGroup(JPanelHomeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLBL))
                .addGap(15, 15, 15))
        );

        routinglb.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        routinglb.setForeground(new java.awt.Color(0, 51, 51));
        routinglb.setText("first name");

        weightlb1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        weightlb1.setForeground(new java.awt.Color(0, 51, 51));
        weightlb1.setText("Weight");

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel2.setText("work Address");

        JPanelWorkAdd1.setBackground(new java.awt.Color(255, 255, 255));

        cityLbl3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        cityLbl3.setForeground(new java.awt.Color(0, 51, 51));
        cityLbl3.setText("city");

        zipLBL3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        zipLBL3.setForeground(new java.awt.Color(0, 51, 51));
        zipLBL3.setText("zip code");

        WtxtStreetAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WtxtStreetAdd2ActionPerformed(evt);
            }
        });

        streetaddLBL3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        streetaddLBL3.setForeground(new java.awt.Color(0, 51, 51));
        streetaddLBL3.setText("Street address");

        unitLBL3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        unitLBL3.setForeground(new java.awt.Color(0, 51, 51));
        unitLBL3.setText("unit number");

        phoneLBL3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        phoneLBL3.setForeground(new java.awt.Color(0, 51, 51));
        phoneLBL3.setText("Phone No.");

        stateLBL3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        stateLBL3.setForeground(new java.awt.Color(0, 51, 51));
        stateLBL3.setText("State");

        javax.swing.GroupLayout JPanelWorkAdd1Layout = new javax.swing.GroupLayout(JPanelWorkAdd1);
        JPanelWorkAdd1.setLayout(JPanelWorkAdd1Layout);
        JPanelWorkAdd1Layout.setHorizontalGroup(
            JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelWorkAdd1Layout.createSequentialGroup()
                .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JPanelWorkAdd1Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(WtxtState2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(WtxtZip2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(WtxtPhone2, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(JPanelWorkAdd1Layout.createSequentialGroup()
                            .addGap(245, 245, 245)
                            .addComponent(WtxtUnitNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelWorkAdd1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateLBL3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPanelWorkAdd1Layout.createSequentialGroup()
                                    .addComponent(cityLbl3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(WtxtCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(unitLBL3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JPanelWorkAdd1Layout.createSequentialGroup()
                                    .addComponent(streetaddLBL3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(WtxtStreetAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(zipLBL3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLBL3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        JPanelWorkAdd1Layout.setVerticalGroup(
            JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelWorkAdd1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WtxtStreetAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetaddLBL3))
                .addGap(18, 18, 18)
                .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WtxtUnitNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitLBL3))
                .addGap(18, 18, 18)
                .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WtxtCity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLbl3))
                .addGap(18, 18, 18)
                .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WtxtState2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLBL3))
                .addGap(18, 18, 18)
                .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WtxtZip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipLBL3))
                .addGap(18, 18, 18)
                .addGroup(JPanelWorkAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WtxtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLBL3))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backbtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(banknamelb)
                                .addGap(12, 12, 12)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(accountlb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(81, 81, 81))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(routinglb, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(JPanelHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(195, 195, 195)
                                        .addComponent(savebtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JPanelWorkAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(updatebtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(193, 193, 193)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(balancelb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(weightlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtFirstName, txtLastName, txtSSN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balancelb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightlb1)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accountlb)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(routinglb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknamelb))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPanelHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(savebtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPanelWorkAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updatebtnv)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {savebtnv, updatebtnv});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAge, txtFirstName, txtLastName, txtSSN});

    }// </editor-fold>//GEN-END:initComponents

    private void backbtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnvActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        Component[] panelStack = userProcessContainer.getComponents();//get list of all panels in userprocesscontainer
        JPanel lastPanel=(JPanel)panelStack[panelStack.length-1];//get last panel 
        ManagePersons manageAccounts = (ManagePersons) lastPanel; 
        manageAccounts.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnvActionPerformed

    private void savebtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnvActionPerformed
        // TODO add your handling code here:
        // getting text from text fields
        
          //getting values for     
        long SSN;
        int age;
        double weight;
        
        String firstName= txtFirstName.getText();
        String lastName= txtLastName.getText();
        
        try{
            SSN= Long.parseLong(txtSSN.getText());
            age = Integer.parseInt(txtAge.getText());
            weight = Double.parseDouble(txtWeight.getText());
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please check the SSN , age and weight input. They should me numbers", "Warning", JOptionPane.WARNING_MESSAGE);
            return;//validation for balance input text field 
        }
        
        
        // geting test feilds of home address
         String hStreet = HtxtStreetAdd.getText();
         String hUnit = HtxtUnitNo.getText();
         String hCity = HtxtCity.getText();
         String hState = HtxtState.getText();
         String hZip = HtxtZip.getText();       
         String hPhone = HtxtPhone.getText();
        
        //getting values of work address
        String wStreet = WtxtStreetAdd2.getText();
        String wUnit = WtxtUnitNo2.getText();
        String wCity = WtxtCity2.getText();
        String wState = WtxtState2.getText();
        String wZip = WtxtZip2.getText();
        String wPhone = WtxtPhone2.getText();
        
        
      
         if(firstName.isBlank() || lastName.isBlank())
        {
            JOptionPane.showMessageDialog(this,"All fields are mandatory","Error",JOptionPane.ERROR_MESSAGE);
            //validification for create person , checking if the text fields are empty
            //stops the process if it's empty
            return;
        }
        
        
        // validation for home address and work address
         
        if(hStreet.isBlank()||hUnit.isBlank()||hCity.isBlank()||hState.isBlank()||hZip.isBlank()||hPhone.isBlank()){
            JOptionPane.showMessageDialog(this,"All work address feilds are mandatory","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(wStreet.isBlank()|| wUnit.isBlank()|| wCity.isBlank()||wState.isBlank()||wZip.isBlank()|| wPhone.isBlank()){
            JOptionPane.showMessageDialog(this,"All work address feilds are mandatory","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        //updating the directory
                    
         
        
        
        //setting person from save button
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setSSN(SSN);
        person.setAge(age);
       
        
        person.getHomeAddress().setStreetAddress(hStreet);
        person.getHomeAddress().setUnitNumber(hUnit);
        person.getHomeAddress().setCity(hCity);
        person.getHomeAddress().setState(hState);
        person.getHomeAddress().setZipCode(hZip);
        person.getHomeAddress().setPhoneNumber(hPhone);


        person.getWorkAddress().setStreetAddress(wStreet);
        person.getWorkAddress().setUnitNumber(wUnit);
        person.getWorkAddress().setCity(wCity);
        person.getWorkAddress().setState(wState);
        person.getWorkAddress().setZipCode(wZip);
        person.getWorkAddress().setPhoneNumber(wPhone);
        
        
        //address objects for home and work
        
//        Address homeAddup = new Address(hStreet, hUnit, hCity,hState,hZip,hPhone);
//        Address workAddup = new Address(wStreet, wUnit, wCity,wState,wZip,wPhone);
//        
        //setting home address and work address for the person class
        
       //dialog box for profile success messsge
        JOptionPane.showMessageDialog(null,"Account update successful","Sucess",JOptionPane.WARNING_MESSAGE);
        setViewMode();  
        
    }//GEN-LAST:event_savebtnvActionPerformed

    private void updatebtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnvActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_updatebtnvActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void HtxtStreetAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HtxtStreetAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HtxtStreetAddActionPerformed

    private void WtxtStreetAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WtxtStreetAdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WtxtStreetAdd2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HtxtCity;
    private javax.swing.JTextField HtxtPhone;
    private javax.swing.JTextField HtxtState;
    private javax.swing.JTextField HtxtStreetAdd;
    private javax.swing.JTextField HtxtUnitNo;
    private javax.swing.JTextField HtxtZip;
    private javax.swing.JPanel JPanelHomeAdd;
    private javax.swing.JPanel JPanelWorkAdd;
    private javax.swing.JPanel JPanelWorkAdd1;
    private javax.swing.JTextField WtxtCity1;
    private javax.swing.JTextField WtxtCity2;
    private javax.swing.JTextField WtxtPhone1;
    private javax.swing.JTextField WtxtPhone2;
    private javax.swing.JTextField WtxtState1;
    private javax.swing.JTextField WtxtState2;
    private javax.swing.JTextField WtxtStreetAdd1;
    private javax.swing.JTextField WtxtStreetAdd2;
    private javax.swing.JTextField WtxtUnitNo1;
    private javax.swing.JTextField WtxtUnitNo2;
    private javax.swing.JTextField WtxtZip1;
    private javax.swing.JTextField WtxtZip2;
    private javax.swing.JLabel accountlb;
    private javax.swing.JButton backbtnv;
    private javax.swing.JLabel balancelb;
    private javax.swing.JLabel banknamelb;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JLabel cityLbl1;
    private javax.swing.JLabel cityLbl3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel phoneLBL;
    private javax.swing.JLabel phoneLBL1;
    private javax.swing.JLabel phoneLBL3;
    private javax.swing.JLabel routinglb;
    private javax.swing.JButton savebtnv;
    private javax.swing.JLabel stateLBL;
    private javax.swing.JLabel stateLBL1;
    private javax.swing.JLabel stateLBL3;
    private javax.swing.JLabel streetaddLBL;
    private javax.swing.JLabel streetaddLBL1;
    private javax.swing.JLabel streetaddLBL3;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JLabel unitLBL;
    private javax.swing.JLabel unitLBL1;
    private javax.swing.JLabel unitLBL3;
    private javax.swing.JButton updatebtnv;
    private javax.swing.JLabel weightlb1;
    private javax.swing.JLabel zipLBL;
    private javax.swing.JLabel zipLBL1;
    private javax.swing.JLabel zipLBL3;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        //updating the person 
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtSSN.setText(Long.toString(person.getSSN()));
        txtAge.setText(Integer.toString(person.getAge()));
        txtWeight.setText(Double.toString(person.getWeight()));
        
        if(person.getHomeAddress()!=null){
            HtxtStreetAdd.setText(person.getHomeAddress().getStreetAddress());
            HtxtUnitNo.setText(person.getHomeAddress().getUnitNumber());
            HtxtState.setText(person.getHomeAddress().getState());
            HtxtCity.setText(person.getHomeAddress().getCity());
            HtxtZip.setText(person.getHomeAddress().getZipCode());
            HtxtPhone.setText(person.getHomeAddress().getPhoneNumber());
            
        }
        
        if(person.getWorkAddress()!=null){
            WtxtStreetAdd2.setText(person.getWorkAddress().getStreetAddress());
            WtxtUnitNo2.setText(person.getWorkAddress().getUnitNumber());
            WtxtState2.setText(person.getWorkAddress().getState());
            WtxtCity2.setText(person.getWorkAddress().getCity());
            WtxtZip2.setText(person.getWorkAddress().getZipCode());
            WtxtPhone2.setText(person.getWorkAddress().getPhoneNumber());
            
        }          
    }

    private void setViewMode() {
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtAge.setEnabled(false);
        txtSSN.setEditable(false);
        txtWeight.setEditable(false);
        
        HtxtStreetAdd.setEnabled(false);
        HtxtUnitNo.setEnabled(false);
        HtxtCity.setEnabled(false);
        HtxtState.setEnabled(false);
        HtxtZip.setEnabled(false);
        HtxtPhone.setEnabled(false);
        
        WtxtStreetAdd2.setEnabled(false);
        WtxtUnitNo2.setEnabled(false);
        WtxtCity2.setEnabled(false);
        WtxtState2.setEnabled(false);
        WtxtZip2.setEnabled(false);
        WtxtPhone2.setEnabled(false);
        
        savebtnv.setEnabled(false);
        updatebtnv.setEnabled(true);
        //update button is set to work only in view mode
    }
    
    private void setEditMode() {
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtAge.setEnabled(true);
        txtSSN.setEditable(true);
        txtWeight.setEditable(true);
        
        HtxtStreetAdd.setEnabled(true);
        HtxtUnitNo.setEnabled(true);
        HtxtCity.setEnabled(true);
        HtxtState.setEnabled(true);
        HtxtZip.setEnabled(true);
        HtxtPhone.setEnabled(true);
        
        WtxtStreetAdd2.setEnabled(true);
        WtxtUnitNo2.setEnabled(true);
        WtxtCity2.setEnabled(true);
        WtxtState2.setEnabled(true);
        WtxtZip2.setEnabled(true);
        WtxtPhone2.setEnabled(true);
        
        savebtnv.setEnabled(true);
        updatebtnv.setEnabled(false);
        //editing the values because of save button is allowed only in edit mode
    }
    
    
    
         
    
}
