/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author jrswa
 */
public class ViewAccount extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private PersonDirectory accountDirectory;
    private Person account;

    /**
     * Creates new form ViewAccount
     */
    public ViewAccount(JPanel userProcessContainer,PersonDirectory accountDirectory,Person account) {
        
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.account = account;
        
        refreshTextFields();// populate text fields
        setViewMode();//view mode
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        routinglbV = new javax.swing.JLabel();
        accnumlbV = new javax.swing.JLabel();
        banknumlbv = new javax.swing.JLabel();
        routingtxtv = new javax.swing.JTextField();
        accounttxtv = new javax.swing.JTextField();
        banknametxtv = new javax.swing.JTextField();
        savebtnv = new javax.swing.JButton();
        updatebtnv = new javax.swing.JButton();
        backbtnv = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Accounts");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        routinglbV.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        routinglbV.setText("Routing Number");

        accnumlbV.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        accnumlbV.setText("Account Number");

        banknumlbv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        banknumlbv.setText("Bank Name");

        routingtxtv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N

        accounttxtv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N

        banknametxtv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        banknametxtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banknametxtvActionPerformed(evt);
            }
        });

        savebtnv.setBackground(new java.awt.Color(0, 0, 0));
        savebtnv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        savebtnv.setForeground(new java.awt.Color(204, 204, 255));
        savebtnv.setText("Save");
        savebtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnvActionPerformed(evt);
            }
        });

        updatebtnv.setBackground(new java.awt.Color(0, 0, 0));
        updatebtnv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        updatebtnv.setForeground(new java.awt.Color(204, 204, 255));
        updatebtnv.setText("Update");
        updatebtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnvActionPerformed(evt);
            }
        });

        backbtnv.setBackground(new java.awt.Color(0, 0, 0));
        backbtnv.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        backbtnv.setForeground(new java.awt.Color(204, 204, 255));
        backbtnv.setText("<<<Back");
        backbtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accnumlbV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banknumlbv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(routinglbV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savebtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(updatebtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accounttxtv)
                            .addComponent(routingtxtv, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknametxtv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(backbtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {accnumlbV, banknumlbv, routinglbV});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {accounttxtv, banknametxtv, routingtxtv});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routinglbV)
                    .addComponent(routingtxtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accnumlbV)
                    .addComponent(accounttxtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banknumlbv)
                    .addComponent(banknametxtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtnv))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {accnumlbV, banknumlbv, routinglbV});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {savebtnv, updatebtnv});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {accounttxtv, banknametxtv, routingtxtv});

    }// </editor-fold>//GEN-END:initComponents

    private void backbtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnvActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        Component[] panelStack = userProcessContainer.getComponents();//get list of all panels in userprocesscontainer
        JPanel lastPanel=(JPanel)panelStack[panelStack.length-1];//get last panel 
        ManageAccounts manageAccounts = (ManageAccounts) lastPanel; 
        manageAccounts.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnvActionPerformed

    private void savebtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnvActionPerformed
        // TODO add your handling code here:
        // getting text from text fields
        String routingNumber= routingtxtv.getText();
        String accountNumber = accounttxtv.getText();
        String bankName = banknametxtv.getText();
        
        if(routingNumber.isBlank() || accountNumber.isBlank() || bankName.isBlank())
        {//verifying if text feilds are blank
            JOptionPane.showMessageDialog(null,"All fields are mandatory");
            return;
        }
        
        //updating the directory
        account.setRountingNumber(routingNumber);
        account.setAccountNumber(accountNumber);
        account.setBankName(bankName);
        
        JOptionPane.showMessageDialog(null,"Account update successful","Sucess",JOptionPane.WARNING_MESSAGE);
               
        setViewMode();     
        
        
    }//GEN-LAST:event_savebtnvActionPerformed

    private void banknametxtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banknametxtvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banknametxtvActionPerformed

    private void updatebtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnvActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_updatebtnvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accnumlbV;
    private javax.swing.JTextField accounttxtv;
    private javax.swing.JButton backbtnv;
    private javax.swing.JTextField banknametxtv;
    private javax.swing.JLabel banknumlbv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel routinglbV;
    private javax.swing.JTextField routingtxtv;
    private javax.swing.JButton savebtnv;
    private javax.swing.JButton updatebtnv;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        routingtxtv.setText(account.getRountingNumber());
        accounttxtv.setText(account.getAccountNumber());
        banknametxtv.setText(account.getBankName());
    }

    private void setViewMode() {
        routingtxtv.setEnabled(false);
        accounttxtv.setEnabled(false);
        banknametxtv.setEnabled(false);
        
        savebtnv.setEnabled(false);
        updatebtnv.setEnabled(true);
        //update button is set to work only in view mode
    }
    
    private void setEditMode() {
        routingtxtv.setEnabled(true);
        accounttxtv.setEnabled(true);
        banknametxtv.setEnabled(true);
        
        savebtnv.setEnabled(true);
        updatebtnv.setEnabled(false);
        //editing routing no, account no, bank name save button is allowed only in edit mode
    }
}
