/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.Person;
import model.PersonDirectory;
import ui.PersonManager.PersonMngWorkArea;

/**
 *
 * @author jrswa
 */
public class MainJFrameAssignment extends javax.swing.JFrame {
    
    private PersonDirectory personDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrameAssignment() {
        initComponents();
        
        this.personDirectory=new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        userProcessContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAccountMng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setMinimumSize(new java.awt.Dimension(93, 80));

        topJPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnAccountMng.setBackground(new java.awt.Color(0, 0, 0));
        btnAccountMng.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnAccountMng.setForeground(new java.awt.Color(204, 204, 255));
        btnAccountMng.setText("start here");
        btnAccountMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(btnAccountMng, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnAccountMng, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        userProcessContainer.add(jPanel1, "card2");

        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountMngActionPerformed
        // TODO add your handling code here:
        PersonMngWorkArea panel = new PersonMngWorkArea(userProcessContainer,personDirectory);
        userProcessContainer.add("PersonMngWorkArea", panel);//adding this panel to container
        
        //adding in userprocessorcontainer for switching view
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      
    }//GEN-LAST:event_btnAccountMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountMng;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {// adding demo data which will be present at the start 
//        Address homeAddress1 = new Address("vinal Street", "apt 2","Boston","MA","02134","9083049809");
//        Address workAddress1 = new Address("Parker Hill", "apt 2","Boston","MA","02120","98779848465");
//        
        Person newPerson1 = personDirectory.addPerson();
        newPerson1.setFirstName("Aman");
        newPerson1.setLastName("Raj");
        newPerson1.setSSN(901289388);
        newPerson1.setAge(19);
        newPerson1.setWeight(60.8);
        
        
        newPerson1.getHomeAddress().setStreetAddress("vinal street");
        newPerson1.getHomeAddress().setUnitNumber("apt 2");
        newPerson1.getHomeAddress().setCity("Boston");
        newPerson1.getHomeAddress().setState("MA");
        newPerson1.getHomeAddress().setZipCode("02130");
        newPerson1.getHomeAddress().setPhoneNumber("9083049809");
        
        newPerson1.getWorkAddress().setStreetAddress("Parker Hill");
        newPerson1.getWorkAddress().setUnitNumber("apt 2");
        newPerson1.getWorkAddress().setCity("Boston");
        newPerson1.getWorkAddress().setState("MA");
        newPerson1.getWorkAddress().setZipCode("02121");
        newPerson1.getWorkAddress().setPhoneNumber("9065154155");



       
       
        
        Person newPerson2 = personDirectory.addPerson();
        newPerson2.setFirstName("Deepika");
        newPerson2.setLastName("Dwarka");
        newPerson2.setSSN(454147864);
        newPerson2.setAge(25);
        newPerson2.setWeight(70);
        
        
        newPerson2.getHomeAddress().setStreetAddress("longwood");
        newPerson2.getHomeAddress().setUnitNumber("apt 4");
        newPerson2.getHomeAddress().setCity("Boston");
        newPerson2.getHomeAddress().setState("MA");
        newPerson2.getHomeAddress().setZipCode("02170");
        newPerson2.getHomeAddress().setPhoneNumber("9878997846");
        
        newPerson2.getWorkAddress().setStreetAddress("Huntington");
        newPerson2.getWorkAddress().setUnitNumber("8");
        newPerson2.getWorkAddress().setCity("Boston");
        newPerson2.getWorkAddress().setState("MA");
        newPerson2.getWorkAddress().setZipCode("02129");
        newPerson2.getWorkAddress().setPhoneNumber("9065154155");

        
        
        
    }
}
