/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.Person;
import model.PersonDirectory;
import ui.PersonManager.PersonMngWorkArea;

/**
 *
 * @author jrswa
 */
public class MainJFrameAssignment extends javax.swing.JFrame {
    
    private PersonDirectory personDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrameAssignment() {
        initComponents();
        
        this.personDirectory=new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        userProcessContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAccountMng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setMinimumSize(new java.awt.Dimension(93, 80));

        topJPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnAccountMng.setBackground(new java.awt.Color(0, 0, 0));
        btnAccountMng.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        btnAccountMng.setForeground(new java.awt.Color(204, 204, 255));
        btnAccountMng.setText("start here");
        btnAccountMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(btnAccountMng, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnAccountMng, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        userProcessContainer.add(jPanel1, "card2");

        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountMngActionPerformed
        // TODO add your handling code here:
        PersonMngWorkArea panel = new PersonMngWorkArea(userProcessContainer,personDirectory);
        userProcessContainer.add("PersonMngWorkArea", panel);//adding this panel to container
        
        //adding in userprocessorcontainer for switching view
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      
    }//GEN-LAST:event_btnAccountMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrameAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountMng;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {// adding 5 demo data which will be present at the start 
//       
        

        //adding first person
        Person newPerson1 = personDirectory.addPerson();
        newPerson1.setFirstName("Aman");
        newPerson1.setLastName("Raj");
        newPerson1.setSSN(901289388);
        newPerson1.setAge(19);
        newPerson1.setWeight(60.8);
        
        Address homeAdd1= new Address();
        homeAdd1.setStreetAddress("vinal street");
        homeAdd1.setUnitNumber("apt 2");
        homeAdd1.setCity("Boston");
        homeAdd1.setState("MA");
        homeAdd1.setZipCode("02130");
        homeAdd1.setPhoneNumber("9083049809");
        newPerson1.setHomeAddress(homeAdd1);
        
        Address workAdd1= new Address();
        workAdd1.setStreetAddress("vinal street");
        workAdd1.setUnitNumber("apt 2");
        workAdd1.setCity("Chicago");
        workAdd1.setState("MA");
        workAdd1.setZipCode("026789");
        workAdd1.setPhoneNumber("9083049809");
        newPerson1.setWorkAddress(workAdd1);
        
        
        
        //second person
        Person newPerson2 = personDirectory.addPerson();
        newPerson2.setFirstName("Monica");
        newPerson2.setLastName("Geller");
        newPerson2.setSSN(678892635);
        newPerson2.setAge(29);
        newPerson2.setWeight(55);
        
        Address homeAdd2= new Address();
        homeAdd2.setStreetAddress("Central Park ");
        homeAdd2.setUnitNumber("apt 2");
        homeAdd2.setCity("NYC");
        homeAdd2.setState("NY");
        homeAdd2.setZipCode("029881");
        homeAdd2.setPhoneNumber("98127987799");
        newPerson2.setHomeAddress(homeAdd2);
        


        Address workAdd2= new Address();
        workAdd2.setStreetAddress("Chef's restaurant");
        workAdd2.setUnitNumber("9");
        workAdd2.setCity("NYC");
        workAdd2.setState("NY");
        workAdd2.setZipCode("098347");
        workAdd2.setPhoneNumber("6546848554");
        newPerson2.setWorkAddress(workAdd2);
        
        
        
        
        //3rd person
        Person newPerson3 = personDirectory.addPerson();
        newPerson3.setFirstName("Harvey");
        newPerson3.setLastName("Spectre");
        newPerson3.setSSN(561654455);
        newPerson3.setAge(29);
        newPerson3.setWeight(59);
        
        Address homeAdd3= new Address();
        homeAdd3.setStreetAddress("Central Park ");
        homeAdd3.setUnitNumber("apt 2");
        homeAdd3.setCity("NYC");
        homeAdd3.setState("NY");
        homeAdd3.setZipCode("029881");
        homeAdd3.setPhoneNumber("65468484874");
        newPerson3.setHomeAddress(homeAdd3);
        


        Address workAdd3= new Address();
        workAdd3.setStreetAddress("Raulph Laren");
        workAdd3.setUnitNumber("7");
        workAdd3.setCity("NYC");
        workAdd3.setState("NY");
        workAdd3.setZipCode("465464");
        workAdd3.setPhoneNumber("984848484848");
        newPerson3.setWorkAddress(workAdd3);
        
        
        //4th person

        Person newPerson4 = personDirectory.addPerson();
        newPerson4.setFirstName("Shri");
        newPerson4.setLastName("Varhinni");
        newPerson4.setSSN(987239847);
        newPerson4.setAge(33);
        newPerson4.setWeight(70);
        
        Address homeAdd4= new Address();
        homeAdd4.setStreetAddress(" Manhattan");
        homeAdd4.setUnitNumber("apt 1");
        homeAdd4.setCity("NYC");
        homeAdd4.setState("NY");
        homeAdd4.setZipCode("025154");
        homeAdd4.setPhoneNumber("5465456454");
        newPerson4.setHomeAddress(homeAdd4);
        

        
        Address workAdd4= new Address();
        workAdd4.setStreetAddress("Palentientology");
        workAdd4.setUnitNumber("9");
        workAdd4.setCity("Los Angles");
        workAdd4.setState("CaliFornia");
        workAdd4.setZipCode("454544");
        workAdd4.setPhoneNumber("87878548894");
        newPerson4.setWorkAddress(workAdd4);
       
        
        
        
        //5th Person
        Person newPerson5 = personDirectory.addPerson();
        newPerson5.setFirstName("Mike");
        newPerson5.setLastName("Ross");
        newPerson5.setSSN(879879877);
        newPerson5.setAge(35);
        newPerson5.setWeight(70);
        
        Address homeAdd5= new Address();
        homeAdd5.setStreetAddress(" Manhattan");
        homeAdd5.setUnitNumber("spt 4");
        homeAdd5.setCity("Dallas");
        homeAdd5.setState("Texas");
        homeAdd5.setZipCode("094998");
        homeAdd5.setPhoneNumber("282512511");
        newPerson5.setHomeAddress(homeAdd5);
        
        Address workAdd5= new Address();
        workAdd5.setStreetAddress("Junior Partner");
        workAdd5.setUnitNumber("8");
        workAdd5.setCity("Seatle");
        workAdd5.setState("California");
        workAdd5.setZipCode("584556");
        workAdd5.setPhoneNumber("5544455555");
        newPerson5.setWorkAddress(workAdd5);
        
        

        
        
        
    }
}
